version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      # - "67:67/udp" # Será necessário apenas se você estiver usando o Pi-hole como seu servidor DHCP
      - "80:80/tcp"
    environment:
      TZ: 'America/Sao-Paulo'
      # WEBPASSWORD: 'defina uma senha segura aqui ou será aleatória'
    # Os volumes armazenam seus dados entre atualizações de contêiner
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN # Necessário se você estiver usando Pi-hole como seu servidor DHCP, caso contrário não é necessário.
    restart: unless-stopped
    networks:
       testDNS:
        ipv4_address: 10.7.5.4
networks:
  testDNS:
    external: 
      name: testDNS